ALGORITHM="hpi"

echo "0.01-0.39"
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.01
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.02
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.03
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.04
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.05
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.06
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.07
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.08
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.09
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.1
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.11
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.12
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.13
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.14
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.15
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.16
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.17
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.18
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.19
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.2
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.21
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.22
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.23
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.24
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.25
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.26
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.27
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.28
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.29
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.3
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.31
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.32
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.33
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.34
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.35
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.36
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.37
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.38
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.39

echo
echo "0.41-0.74"
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.41
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.42
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.43
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.44
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.45
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.46
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.47
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.48
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.49
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.5
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.51
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.52
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.53
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.54
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.55
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.56
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.57
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.58
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.59
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.6
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.61
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.62
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.63
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.64
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.65
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.66
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.67
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.68
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.69
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.7
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.71
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.72
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.73
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.74

echo 
echo "0.76-0.99"
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.76
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.77
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.78
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.79
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.8
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.81
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.82
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.83
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.84
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.85
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.86
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.87
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.88
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.89
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.9
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.91
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.92
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.93
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.94
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.95
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.96
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.97
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.98
python3 planner.py --mdp mdp.txt --algorithm ${ALGORITHM} --discount 0.99
